
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[bar/mrbar]
width = 100%
height = 25pt
radius = 

bottom = false
fixed-center = true

offset-x = %
offset-y = 1%

module-margin-left = 0
module-margin-right = 0

override-redirect = false
wm-name =

dpi = 104

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

padding-left = 1
padding-right = 1.2

module-margin = 0

; text
font-0 = "scientifica:size=7;4"
; icons
font-1 = "Symbols Nerd Font:size=7;4"
; glyph
font-2 = "Symbols Nerd Font:size=30;4"
; dot
font-3 = "Symbols Nerd Font:size=7.2;4"
; clock & mpd
font-4 = "scientifica:style=bold:size=7;4"
; Archcraft
font-5 = "Symbols Nerd Font:size=7;4"


modules-left =  sep2 menu sep0 xworkspaces sep0 filesystem sep0 keyboard sep1 tray
modules-center = sep2 user  sep0  date sep1
modules-right = sep2 cpu sep0 memory sep0 ethernet sep0 volume sep0 nofication sep1
